import { createElement } from '@lwc/engine-dom';
import XLP_POC_EmailDropForwarder from 'c/xLP_POC_EmailDropForwarder';

describe('c-x-l-p-p-o-c-email-drop-forwarder', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-x-l-p-p-o-c-email-drop-forwarder', {
            is: XLP_POC_EmailDropForwarder
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});